<?xml version="1.0"?>
<package format="3">
  <name>projectairsim_ros2_cpp</name>
  <version>0.1.0</version>
  <description>ROS 2 bridge for Project AirSim using the C++ client API.</description>

  <maintainer email="todo@microsoft.com">To Do</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp</depend>
  <depend>rosgraph_msgs</depend>
  <depend>rosidl_runtime_cpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
