controller_list:
  - name: multi_dof_joint_trajectory_action
    action_ns: multi_dof_follow_joint_trajectory
    type: MultiDofFollowJointTrajectory
    default: true
    joints:
      - virtual_joint
